name: F4zt Automation

on: 
  push:
      branches: [ "main" ]

  workflow_dispatch: 

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: "Show message"
        run: echo "Hello world"
        